
trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04' # 运行环境

steps:
- task: NodeTool@0 
  inputs:
    versionSpec: '10.x'
  displayName: 'Installing Node.js...'

- task: InstallSSHKey@0
  inputs:
    hostName: github.com,52.74.223.119 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
    sshPublicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCx/TN15LaHnqDt3HrMeYAzW7mM83cTgIG8b6NlZ7ZG7Fv515uR1xhX8vk7JcxQxAb8+bq1CjK4lFQc+a/cWrXUuCbQnxp5wdDZWDuMDAXGu22irOfcceEMEU0GMM096mSBFPdfWBkGpuHQAq4DeiP+kJFLA3WymcksDtput6CAZpSkwzopwi8TIkIApvnV4umMIeNo5d+46ulPuAC2OPhkXQ/++xtgLP8u60zQbJGOnwGEwFHJeBS44V6oj7tKOGaK+GdYQrq0kllwTCd9mm2DQmCigFxhcd32q999SyBUoewOFrMYhCPhL6CS2VURnL+3tndMxKQx7rlsxJIhrwIj 1242937438@qq.com
    sshKeySecureFile: id_rsa
  displayName: 'Installing SSH...'

# 安装gitbook脚手架，
- script: |
    npm install gitbook-cli -g;
    gitbook install;
    gitbook build
  displayName: 'Installing dependencies...'

# 托管仓库需要部署
- script:
    ssh-keyscan -t rsa e.coding.net >> ~/.ssh/known_hosts
    git remote add coding git@e.coding.net:chenhao2020/book1/book1.git;
    git remote add upstream git@github.com:chenhao2020/chenhao2020.github.io.git;
    cp -R _book/* .;
    rm -rf node_modules;
    rm -rf _book;
    rm -rf azure-pipelines.yml;
    git config --global user.name "chenhao2020";
    git config --global user.email "1242937438@qq.com";
    git checkout -b gh-pages;
    git add .;
    git commit -m 'Update docs';
    git push upstream gh-pages --force
    git push coding master --force
  displayName: 'Deploying...'

# 安全测试
# - task: WhiteSource Bolt@20
#  displayName: 'Run WhiteSource Bolt'
  