
trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04' # 运行环境

steps:
- task: NodeTool@0 
  inputs:
    versionSpec: '10.x'
  displayName: 'Installing Node.js...'

- task: InstallSSHKey@0
  inputs:
    hostName: github.com,13.229.188.59 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
    sshPublicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQD2NI8FtHycQPEYZmOvBBzl+cWIfFnCxf8i1nIjoCcQl9zF+ae0uuSAIPsNuMc1+o45toOXTx/Bne+5SJUIVIVrfKtR5eYDbV/wrVEkxCrluU9QYwPloI12/vYXjTf7nkpvlJgOorKQLVfHF/oIqS0Nxh6cEFTm9Nkw1QuU1gPPIha6TapRCmH88dBUaNbY77uGcazqFwUdCIEHJzlQb9p7Zf80qLSOAlCsxYBy8IljBN2trEtjNp2TqdGVffcq6WArF5/NlC3iTku3LNu0JcXjHwTriITkbqNmieVvknZz1Y8YHd+0YUyE+nSUcnbLrCd/qfG5J8RSJiQ2Q9lLZhBnfQ/XWTAOw96bue9KfgK4wyDrIMdlDqbk5eRwhi7RIUUV+TG+emZgvY+Ooofusge9b3WilUAXf0r/cVP0+rAjhqqGcgMEoaQdqmI+L3FYPSs0N9jI1fKEVYoVFFmANQ7cZ7Ohs2EOdpnlGN3t9MX7dorYQdsFLU4tc+Sgj1oNBFM= 1242937438@qq.com
    sshKeySecureFile: id_rsa
  displayName: 'Installing SSH...'

# 安装gitbook脚手架，
- script: |
    npm install gitbook-cli -g;
    gitbook build;
    pwd;
    ls -a
  displayName: 'Installing dependencies...'

# 托管仓库需要部署
- script:
    ls _book/;
    git remote add upstream https://github.com/chenhao2020/bookfortest.git;
    git remote -v;
    cp -R _book/* .;
    git config --global user.name "chenhao2020";
    git config --global user.email "1242937438@qq.com";
    git add .;
    git commit -m 'Initial Commit';
    git status;
    git log --oneline;
    git push -u upstream chenhao2020 --force
  displayName: 'Deploying...'
  